Taka1304/egh-team20

- package.json
- src/app/_features/Navigate/Header/Header.tsx
- src/app/_features/Navigate/Header/HeaderView.tsx
- src/app/sandbox/page.tsx
- src/components/ui/avatar.tsx
- src/components/ui/button.tsx
- src/components/ui/input.tsx
- src/lib/utils.ts
- tailwind.config.ts
> #1 [Feat✨] Headerコンポーネントの実装 

- src/app/_features/Navigate/Header/HeaderView.tsx
- src/app/globals.css
- tailwind.config.ts
darkモード等の対応を可能にするために、global.cssに色を追加し、tailwind.config.tsのハードコーディング部分を削除
- Close #6
> #6 [Refactor ♻️] テーマ対応のためにtailwind.cssの色指定を変更する 

- src/app/_features/AIReviewDialog/AIReviewDialog.tsx
- src/app/_features/RichEditor/TemplateDialog/TemplateDialogView.tsx
- src/app/reports/[reportId]/publish/page.tsx
- src/app/reports/new/page.tsx
> #48 [Feat✨]日報投稿ページAI添削結果表示UIの作成と、確認ページのAI添削の削除 

- src/app/_features/Modal/ReportModalView.tsx
日付のコンポーネントを使用した
なし
かわらず
コンポーネントが使われてなかった
コンポーネントが使用された
なし
なし
> 日付のコンポーネントに変更

- prisma/migrations/20250225035936_badge/migration.sql
- prisma/schema.prisma
- src/app/api/[[...route]]/reports/index.ts
- src/app/api/[[...route]]/route.ts
日報投稿APIの実装
Session必須
- Close #30
> #30 日報投稿API実装

- src/app/[username]/page.tsx
- src/app/_features/RecommendedUsers/RecommendedUserCard.tsx
- src/app/_features/RecommendedUsers/RecommendedUsers.tsx
- src/app/_features/TimeLine/TimeLineView.tsx
- src/app/globals.css
ProfileにTimeLineを導入
- Close #46 
Profileのみ
TimeLineとProfileになった
なし
なし
> timeLine導入

- prisma/schema.prisma
- src/app/api/[[...route]]/reports/index.ts
日報の詳細取得API
アクセス制限
- VisibilityがPUBLICなら、非ログイン含め全員閲覧可。
- VisibilityがFOLLOWERSなら、投稿者のフォロワーなら閲覧可能。
- VisibilityがPRIVATEなら、投稿者のみ
- Close #31 
```
{
"report": {
"id": "cm7jzamnu0001ux6w2ugc2ysf",
"text": "やったこと\nこれこれこれ\n\nあれあれあれ",
"title": "日報: 2025/02/25",
"formatId": null,
"goalId": null,
"visibility": "PUBLIC",
"learningTime": 0,
"pomodoroCount": 0,
"user": {
"id": "cm7hceqgd0002ux8873ysihbc",
"displayName": null,
"image": "https://avatars.githubusercontent.com/u/87125870?v=4",
"isPrivate": false
},
"reactions": [
{
"id": "cm7k363ah0000r0uxfxtyhegi",
"type": { "id": "cm7k363aj0001r0ux0ff4361n", "name": "heart" },
"user": {
"id": "cm7hceqgd0002ux8873ysihbc",
"displayName": null,
"image": "https://avatars.githubusercontent.com/u/87125870?v=4"
}
},
{
"id": "cm7k363aj0003r0uxd052fqom",
"type": …
```
> #31 日報詳細取得 API実装

- src/app/api/[[...route]]/reports/index.ts
- src/app/api/[[...route]]/utils/index.ts
> #32 日報更新 API 実装

- src/app/api/[[...route]]/users/index.ts
[patch] /user/:id の実装
- Close #25 
* patchとして更新を受け入れる要素が定義している内容で問題ないかどうか
* upsertの使い方が今の実装で問題ないかどうか
* ファイルは分けた方がいい？
* ユーザー名`GH E`のユーザーに対して，今supabaseに保存されている内容と同じものを指定した状態でリクエストして，データベースに変更がないことを確認
* ユーザー名`GH E`のユーザーに対して，displayNameにのみ変更を加えた状態でリクエストして，データベースにdisplayNameが上書きされていることとupdatedAtが更新されていることを確認
> Feature/25 [patch] /user/:id の実装

- prisma/migrations/20250226012718_reation_unique/migration.sql
- prisma/schema.prisma
- src/app/api/[[...route]]/reports/index.ts
Reaction を、userId, typeId, reportIdの複合キーで任意に変更
id列いらねぇなと思ったので削除
- #33 
- #34
> 🗃️ Reactionを一意にする

- src/app/_features/AIReviewDialog/AIReviewDialog.stories.tsx
> #83 [Bug🐛] Storybookの依存関係の修正 

- src/app/error.tsx
- src/app/not-found.tsx
404ページの実装と500ページの実装
- Close #88
> #88 [Feat✨]404ページの実装・500ページの実装 

- src/app/_features/ThemeSwitcher.tsx/ThemeProvider.tsx
next-themesでclassを切り替えた際に、SSRの出力とclientの出力が異なっていたため、useEffectでマウントのタイミングを変更することで解決。
- Close #90
> #90 [Bug🐛] ハイドレーションエラー原因究明

- src/app/_features/TopPage/TopPage.tsx
> TopPageの作成

- src/app/api/[[...route]]/assets/index.ts
- src/app/api/[[...route]]/reports/index.ts
- src/app/api/[[...route]]/route.ts
- src/lib/hono.ts
> hono clientの型推論ができるように修正

- src/app/api/[[...route]]/reports/index.ts
```
{
"reports": [
{
"id": "cm7lya0to0001uxdwhk7kqaw5",
"userId": "cm7hceqgd0002ux8873ysihbc",
"goalId": null,
"formatId": null,
"title": "たいとるだよ",
"text": "<p>本日の日報</p><ul><li><p>日報投稿 APIをつなぎこんだよ</p></li><li><p>アルバイト9時間！</p></li></ul><p>カレーをたべました、おいしかったです（小並感）</p>",
"visibility": "PRIVATE",
"learningTime": 0,
"pomodoroCount": 0,
"createdAt": "2025-02-26T13:27:30.726Z",
"updatedAt": "2025-02-26T13:27:30.726Z"
}
]
}
```
> ✨ 下書き一覧取得API実装

- src/app/_features/ReportCard/ReportCard.stories.tsx
- src/app/_features/ReportCard/ReportCard.tsx
- src/app/_features/Timeline/Timeline.tsx
- src/app/_features/Timeline/TimelineView.tsx
- src/app/globals.css
- src/app/hooks/useReprots.ts
- src/app/page.tsx
- src/app/types/reports.ts
> #100 [Feat✨] / でトップページを実装する 

- src/app/_features/ReportCard/ActionButton/ActionButton.stories.tsx
- src/app/_features/ReportCard/ActionButton/ActionButton.tsx
- src/app/_features/ReportCard/ReportCard.tsx
- src/app/_features/ReportCard/ReportCardView.tsx
リアクションをインクリメント・デクリメントできるようにし、アニメーションも付与
リアクションの色も、theme対応してもいいかも...
- Close #111
> #111 [Feat✨]ReportCardのリアクションを押した際のアニメーション 

- src/app/_features/Navigate/Header/Header.tsx
タイトルの通り、投稿ボタンから投稿ページに遷移
- Close #121
> #121 [Feat✨] 投稿ボタンを押した際に投稿ページに遷移 

- src/app/api/[[...route]]/reports/index.ts
> ✨ リアクションの情報を追加

- src/app/api/[[...route]]/reports/index.ts
> ✨ 日報削除 API 実装

- src/app/Loading.tsx
- src/app/_features/RecommendedArticles/RecommendedArticles.tsx
- src/app/_features/RecommendedArticles/useRecommendedArticles.tsx
- src/app/_features/Timeline/TimelineView.tsx
LoadingUIを追加し、トップページに適用した。
- Close #70
> #70 [Feat✨]ローディングコンポーネントを実装 

- src/app/api/[[...route]]/reactions/index.ts
- src/app/api/[[...route]]/route.ts
リアクションタイプの一覧取得
```
[
{
"id": "cm7k363aj0001r0ux0ff4361n",
"name": "HEART"
},
{
"id": "cm7n45ua20000ksuxdbbi597c",
"name": "FIRE"
},
{
"id": "cm7n45ua40001ksux1x3lbq2m",
"name": "CHECK"
}
]
```
> ✨ /reactions get実装

- src/app/_features/RecommendedArticles/RecommendedArticles.tsx
- src/app/_features/RecommendedArticles/RecommendedArticlesCard.tsx
- src/app/page.tsx
UIだけでも作成
ユーザーレコメンド周りのコンポーネントの修正が必要そう
- Close #137
> #137 [Feat✨] トップページにおすすめユーザー組み込み

- src/app/_features/Login/LoginView.tsx
- src/app/_features/Navigate/Header/UserMenu/UserMenu.tsx
> リダイレクト処理追加、サインアウト実装

- src/app/_features/MarkdownContent/MarkdownContent.tsx
> 🐛 画像が表示されない件を修正

- prisma/migrations/20250227105429_badge/migration.sql
- prisma/migrations/20250227114335_badge_del_updatedat/migration.sql
- prisma/schema.prisma
> 🗃️ badge機能実装、schema変更

- src/app/api/[[...route]]/users/index.ts
jsonを返すようにして，エラー文章を日本語に変更
ただエラーハンドリングの部分を修正しただけ
> refact: [get]/users/:id のエラーハンドリングを修正

- src/app/api/[[...route]]/badges/index.ts
- src/app/api/[[...route]]/route.ts
- src/app/api/[[...route]]/users/index.ts
> ✨ Badgeの情報を反映

- src/app/_features/Pomodoro/HourglassTimer/HourglassTimerView.tsx
砂時計のアニメーションを物理法則に沿わせた。
- Close #139
> #139 [Feat✨]砂時計のアニメーション修正 

- src/app/_features/Profile/ProfileCard/ProfileCard.tsx
- src/app/_features/Profile/ProfileRecommendedUsers/ProfileRecommendedUsers.tsx
- src/app/_features/Profile/ProfileRecommendedUsers/ProfileRecommendedUsersCard/ProfileRecommendedUserCard.tsx
- src/app/_features/RecommendedUsers/RecommendedUserCard.tsx
- src/app/api/[[...route]]/users/index.ts
- src/app/hooks/useRecommendUser.ts
- src/components/ui/button.tsx
> #176 [Bug🐛] おすすめのユーザー表示 

- src/app/_features/Follow/FolloSkeleton.tsx
- src/app/_features/Follow/FollowList.tsx
- src/app/_features/Follow/FollowListItem.tsx
- src/app/_features/Follow/FollowPageContainer.tsx
- src/app/_features/Follow/FollowTabs.tsx
- src/app/_features/Profile/ProfileCard/ProfileCard.tsx
- src/app/api/[[...route]]/users/index.ts
- src/app/hooks/useFollowUsers.ts
- src/app/profile/[username]/follow/page.tsx
フォロー中・フォロワー確認のUIの作成API組み込み
- Close #178
> #178 [Feat✨]フォロー・フォロワー確認UI 

- src/app/_features/ReportCard/ReportCard.tsx
- src/app/_features/ReportCard/ReportCardView.tsx
タイムラインのテキストの切り取り対策に、サイズによるリサイズと文字数リサイズを追加
- Close #187
> #187 [Bug🐛] タイムラインのテキストが切り取られているのを修正 

- src/app/_features/Profile/ProfilePage/ProfilePageView.tsx
フォロー・フォロワーを確認するページの作成
- Close #184
> #184 [Bug🐛] プロフィールページ読み込み時のUIバグ修正 

- src/app/api/[[...route]]/users/index.ts
```
{
"data": [
{
"date": "2025-02-28T00:00:00.000Z",
"count": 4
},
{
"date": "2025-02-27T00:00:00.000Z",
"count": 4
},
{
"date": "2025-02-26T00:00:00.000Z",
"count": 5
},
{
"date": "2025-02-25T00:00:00.000Z",
"count": 1
}
]
}
```
- Close #200
> ✨ /users/:id/contributions を実装

- prisma/migrations/20250228160616_recommended_article/migration.sql
- prisma/schema.prisma
AIレコメンドのためのモデルを定義
```
model RecommendedArticle {
id        String   @id @default(cuid()) // 一意のID
userId    String // User モデルの ID
url       String // 記事のURL
user      User     @relation(fields: [userId], references: [id], onDelete: Cascade) // ユーザーとのリレーション
createdAt DateTime @default(now()) // 登録日時
updatedAt DateTime @updatedAt // 更新日時
}
```
- Close #206 
- scheme.prismaの変更
> feat: AIレコメンドのためのモデル`RecommendedArticle`の定義

- src/app/_features/Timeline/Timeline.tsx
- src/app/_features/Timeline/TimelineView.tsx
- src/app/hooks/useReprots.ts
俺か、カテゴリか、フォロー中か...
- Close #205
> #205 [Feat✨]タイムラインAPI組み込み(全体・フォロー中・自分) 

- src/app/_features/Timeline/TimelineView.tsx
タイムラインを複雑なアニメーションから簡易的なアニメーションに変更
- Close #210
> #210 [Bug🐛] タイムラインのUIが死んだ 

- src/app/_features/RecommendedArticles/RecommendedArticles.tsx
- src/app/_features/RecommendedArticles/RecommendedArticlesCard.tsx
> #209 [Bug🐛] AIレコメンドのUIデグレ修正 

- src/app/_features/ReportCard/ReportCard.stories.tsx
- src/app/_features/ReportCard/ReportCard.tsx
- src/app/_features/ReportCard/ReportCardView.tsx
- src/app/_features/ReportCard/ReportDeleteDialog/ReportDeleteDialog.tsx
- src/app/_features/Timeline/Timeline.tsx
- src/app/_features/Timeline/TimelineView.tsx
- src/app/hooks/useReprots.ts
- src/app/types/reports.ts
日報削除をReportsCardに組み込みました
- Close #98
>  #98 [Feat✨]日報削除のフロント実装

- src/app/hooks/useReprots.ts
日報が存在しない場合に、空の配列を明示的に私、エラーメッセージを表示。
- Close #220
> #220 [Bug🐛] 日報が存在しない時に、日報が存在しないという表示が出ない 

- src/app/_features/ThemeSwitcher/ThemeProvider.tsx
- src/app/_features/ThemeSwitcher/atom.ts
- src/app/globals.css
> #222 [Bug🐛] カラーパレットの文字が表示されていない

- src/app/_features/Profile/ProfilePage/ProfilePageContainer.tsx
- src/app/_features/Profile/ProfilePage/ProfilePageView.tsx
- src/app/_features/Profile/UserCharts/ContinuityChart/ContinuityChart.tsx
- src/app/_features/Profile/UserCharts/PostsChart/PostsChart.tsx
- src/app/_features/Timeline/Timeline.stories.tsx
- src/app/_features/Timeline/Timeline.tsx
- src/app/_features/Timeline/TimelineView.tsx
- src/app/api/users/[id]/stats/route.ts
- src/app/globals.css
- src/app/hooks/useRecommendUser.ts
- src/app/hooks/useUserStats.ts
- src/app/page.tsx
統計情報を取得するAPIの作成と、プロフィールページに配置
タイムラインのデータ取得に対するリサイズ調整
スクロールバーは後日修正
- Close #224
> #224 [Feat✨]プロフィールページに統計情報追加・UI配置変更

- src/app/_features/NotificationModal/NotificationModalView.tsx
- src/app/_features/NotificationModal/useNotifications.tsx
- src/app/api/[[...route]]/notifications/index.ts
- src/app/api/[[...route]]/reports/reaction.ts
- src/app/api/[[...route]]/users/index.ts
> 通知の表示名バグ修正

- src/app/_features/Navigate/Header/Header.tsx
- src/app/_features/Timeline/TimelineView.tsx
Headerのレスポンシブ対応
ボタンをDropdownMenuにまとめる
通知だけ場所変えて表示
Timeline Modeの切り替えがはみ出ていたので、モバイル時はアイコンのみ表示、アクティブ時はテキストも表示する
その他UI調整
> #233 レスポンシブ対応など

- src/app/_features/MarkdownContent/MarkdownContent.tsx
> #234 [Bug🐛] マークダウンの色修正 

- src/app/_features/RecommendedArticles/RecommendedArticles.tsx
- src/app/page.tsx
> #241 [Bug🐛] 非ログイン時に、おすすめ記事を表示しない 

- src/app/_features/ReportEditor/ReportEditorEditContainer.tsx
> 🐛 editから投稿した場合に/reportsに飛ぶバグ修正
